// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RocketMoonApp.Server.Data;

#nullable disable

namespace RocketMoonApp.Server.Migrations
{
    [DbContext(typeof(RocketMoonDbContext))]
    partial class RocketMoonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RocketMoonApp.Server.Models.AnalysisCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoonPhaseCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("SuccessRate")
                        .HasColumnType("REAL");

                    b.Property<int>("SuccessfulLaunches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLaunches")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AnalysisCaches");
                });

            modelBuilder.Entity("RocketMoonApp.Server.Models.Launch", b =>
                {
                    b.Property<string>("LaunchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RocketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LaunchId");

                    b.HasIndex("LocationId");

                    b.ToTable("Launches");
                });

            modelBuilder.Entity("RocketMoonApp.Server.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RocketMoonApp.Server.Models.MoonPhase", b =>
                {
                    b.Property<int>("MoonPhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PhasePercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MoonPhaseId");

                    b.ToTable("MoonPhases");
                });

            modelBuilder.Entity("RocketMoonApp.Server.Models.Launch", b =>
                {
                    b.HasOne("RocketMoonApp.Server.Models.Location", "Location")
                        .WithMany("Launches")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RocketMoonApp.Server.Models.Location", b =>
                {
                    b.Navigation("Launches");
                });
#pragma warning restore 612, 618
        }
    }
}
